//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class DPE_DPE_AdresseType {
    
    public static let namespacePrefix: String? = "DPE"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/DPE_Document/v1.0"
    
    // attributes:
    
    // elements:
    public var Adresse: NFDM_Adresse
    
    // default Constructor
    public init() {
        
        self.Adresse = NFDM_Adresse()
        
    }
    
    // copy Constructor
    public init(_ _DPE_DPE_AdresseType: DPE_DPE_AdresseType ) {
        
        self.Adresse = _DPE_DPE_AdresseType.Adresse
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> DPE_DPE_AdresseType {
        
        let _DPE_DPE_AdresseType = DPE_DPE_AdresseType()
        
        let uriAdresse = NFDM_Adresse.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameAdresse = QName("Adresse", uri: uriAdresse)
        _DPE_DPE_AdresseType.Adresse = NFDM_Adresse.deserialize(infoset.select(qNameAdresse))
        
        return _DPE_DPE_AdresseType
    }
}

extension Optional where Wrapped == DPE_DPE_AdresseType {
    public static func deserialize(_ infoset: Infoset) -> DPE_DPE_AdresseType? {
        if infoset.count == 0 {
            return nil
        } else {
            return DPE_DPE_AdresseType.deserialize(infoset)
        }
    }
}

extension Array where Element: DPE_DPE_AdresseType {
    public var namespaceUri: String? {
        get {
            return DPE_DPE_AdresseType.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [DPE_DPE_AdresseType] {
        return infoset.map { (element: Infoset) in
        DPE_DPE_AdresseType.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

