//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class DPE_DPE_VV_Bevollmaechtigter {
    
    public static let namespacePrefix: String? = "DPE"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/DPE_Document/v1.0"
    
    // attributes:
    
    // elements:
    public var DPE_VV_EMail: String?
    public var DPE_VV_Faxnummer: String?
    public var DPE_VV_Name_Bevollmaechtigter: String
    public var DPE_VV_Vorname_Bevollmaechtigter: String
    public var DPE_VV_Telefon_Bevollmaechtigter: String
    public var DPE_VV_Adresse_Bevollmaechtigter: DPE_DPE_AdresseType
    
    // default Constructor
    public init() {
        
        self.DPE_VV_EMail = nil
        self.DPE_VV_Faxnummer = nil
        self.DPE_VV_Name_Bevollmaechtigter = String()
        self.DPE_VV_Vorname_Bevollmaechtigter = String()
        self.DPE_VV_Telefon_Bevollmaechtigter = String()
        self.DPE_VV_Adresse_Bevollmaechtigter = DPE_DPE_AdresseType()
        
    }
    
    // copy Constructor
    public init(_ _DPE_DPE_VV_Bevollmaechtigter: DPE_DPE_VV_Bevollmaechtigter ) {
        
        self.DPE_VV_EMail = _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_EMail
        self.DPE_VV_Faxnummer = _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_Faxnummer
        self.DPE_VV_Name_Bevollmaechtigter = _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_Name_Bevollmaechtigter
        self.DPE_VV_Vorname_Bevollmaechtigter = _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_Vorname_Bevollmaechtigter
        self.DPE_VV_Telefon_Bevollmaechtigter = _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_Telefon_Bevollmaechtigter
        self.DPE_VV_Adresse_Bevollmaechtigter = _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_Adresse_Bevollmaechtigter
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> DPE_DPE_VV_Bevollmaechtigter {
        
        let _DPE_DPE_VV_Bevollmaechtigter = DPE_DPE_VV_Bevollmaechtigter()
        
        let uriDPE_VV_EMail = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDPE_VV_EMail = QName("DPE_VV_E-Mail", uri: uriDPE_VV_EMail)
        _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_EMail = String?.deserialize(infoset.select(qNameDPE_VV_EMail))
        
        let uriDPE_VV_Faxnummer = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDPE_VV_Faxnummer = QName("DPE_VV_Faxnummer", uri: uriDPE_VV_Faxnummer)
        _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_Faxnummer = String?.deserialize(infoset.select(qNameDPE_VV_Faxnummer))
        
        let uriDPE_VV_Name_Bevollmaechtigter = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDPE_VV_Name_Bevollmaechtigter = QName("DPE_VV_Name_Bevollmaechtigter", uri: uriDPE_VV_Name_Bevollmaechtigter)
        _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_Name_Bevollmaechtigter = String.deserialize(infoset.select(qNameDPE_VV_Name_Bevollmaechtigter))
        
        let uriDPE_VV_Vorname_Bevollmaechtigter = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDPE_VV_Vorname_Bevollmaechtigter = QName("DPE_VV_Vorname_Bevollmaechtigter", uri: uriDPE_VV_Vorname_Bevollmaechtigter)
        _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_Vorname_Bevollmaechtigter = String.deserialize(infoset.select(qNameDPE_VV_Vorname_Bevollmaechtigter))
        
        let uriDPE_VV_Telefon_Bevollmaechtigter = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDPE_VV_Telefon_Bevollmaechtigter = QName("DPE_VV_Telefon_Bevollmaechtigter", uri: uriDPE_VV_Telefon_Bevollmaechtigter)
        _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_Telefon_Bevollmaechtigter = String.deserialize(infoset.select(qNameDPE_VV_Telefon_Bevollmaechtigter))
        
        let uriDPE_VV_Adresse_Bevollmaechtigter = DPE_DPE_AdresseType.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDPE_VV_Adresse_Bevollmaechtigter = QName("DPE_VV_Adresse_Bevollmaechtigter", uri: uriDPE_VV_Adresse_Bevollmaechtigter)
        _DPE_DPE_VV_Bevollmaechtigter.DPE_VV_Adresse_Bevollmaechtigter = DPE_DPE_AdresseType.deserialize(infoset.select(qNameDPE_VV_Adresse_Bevollmaechtigter))
        
        return _DPE_DPE_VV_Bevollmaechtigter
    }
}

extension Optional where Wrapped == DPE_DPE_VV_Bevollmaechtigter {
    public static func deserialize(_ infoset: Infoset) -> DPE_DPE_VV_Bevollmaechtigter? {
        if infoset.count == 0 {
            return nil
        } else {
            return DPE_DPE_VV_Bevollmaechtigter.deserialize(infoset)
        }
    }
}

extension Array where Element: DPE_DPE_VV_Bevollmaechtigter {
    public var namespaceUri: String? {
        get {
            return DPE_DPE_VV_Bevollmaechtigter.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [DPE_DPE_VV_Bevollmaechtigter] {
        return infoset.map { (element: Infoset) in
        DPE_DPE_VV_Bevollmaechtigter.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

