//
//  Copyright (c) 2020 gematik GmbH
//  
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//  
//     http://www.apache.org/licenses/LICENSE-2.0
//  
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

//
//  This file was generated from an xsd file and represents a simple or complex type of it.
//  Generated by a fork of xsd2cocoa (see https://github.com/Daij-Djan/xsd2cocoa) and a specified custom transform template.
//

import Foundation
import XMLTools

// MARK: - Generated file, do not edit. Any edits of this file will be overwritten and thus discarded.
public class DPE_DPE_Gewebe_Organspendeerklaerung {
    
    public static let namespacePrefix: String? = "DPE"
    public static let namespaceUri: String? = "http://ws.gematik.de/fa/nfds/DPE_Document/v1.0"
    
    // attributes:
    public var DPE_GO_letzte_Aktualisierung: String
    
    // elements:
    public var DPE_GO_Ablageort: DPE_DPE_AdresseType?
    public var DPE_GO_Beschreibung: String
    
    // default Constructor
    public init() {
        
        self.DPE_GO_letzte_Aktualisierung = String()
        
        self.DPE_GO_Ablageort = nil
        self.DPE_GO_Beschreibung = String()
        
    }
    
    // copy Constructor
    public init(_ _DPE_DPE_Gewebe_Organspendeerklaerung: DPE_DPE_Gewebe_Organspendeerklaerung ) {
        
        self.DPE_GO_letzte_Aktualisierung = _DPE_DPE_Gewebe_Organspendeerklaerung.DPE_GO_letzte_Aktualisierung
        
        self.DPE_GO_Ablageort = _DPE_DPE_Gewebe_Organspendeerklaerung.DPE_GO_Ablageort
        self.DPE_GO_Beschreibung = _DPE_DPE_Gewebe_Organspendeerklaerung.DPE_GO_Beschreibung
        
    }
    
    public class func deserialize(_ infoset: Infoset) -> DPE_DPE_Gewebe_Organspendeerklaerung {
        
        let _DPE_DPE_Gewebe_Organspendeerklaerung = DPE_DPE_Gewebe_Organspendeerklaerung()
        
        _DPE_DPE_Gewebe_Organspendeerklaerung.DPE_GO_letzte_Aktualisierung = String.deserialize(infoset.attr("DPE_GO_letzte_Aktualisierung"))
        
        let uriDPE_GO_Ablageort = DPE_DPE_AdresseType.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDPE_GO_Ablageort = QName("DPE_GO_Ablageort", uri: uriDPE_GO_Ablageort)
        _DPE_DPE_Gewebe_Organspendeerklaerung.DPE_GO_Ablageort = DPE_DPE_AdresseType?.deserialize(infoset.select(qNameDPE_GO_Ablageort))
        
        let uriDPE_GO_Beschreibung = String.namespaceUri ?? self.namespaceUri ?? infoset.namespaceContext.defaultURI!
        let qNameDPE_GO_Beschreibung = QName("DPE_GO_Beschreibung", uri: uriDPE_GO_Beschreibung)
        _DPE_DPE_Gewebe_Organspendeerklaerung.DPE_GO_Beschreibung = String.deserialize(infoset.select(qNameDPE_GO_Beschreibung))
        
        return _DPE_DPE_Gewebe_Organspendeerklaerung
    }
}

extension Optional where Wrapped == DPE_DPE_Gewebe_Organspendeerklaerung {
    public static func deserialize(_ infoset: Infoset) -> DPE_DPE_Gewebe_Organspendeerklaerung? {
        if infoset.count == 0 {
            return nil
        } else {
            return DPE_DPE_Gewebe_Organspendeerklaerung.deserialize(infoset)
        }
    }
}

extension Array where Element: DPE_DPE_Gewebe_Organspendeerklaerung {
    public var namespaceUri: String? {
        get {
            return DPE_DPE_Gewebe_Organspendeerklaerung.namespaceUri
        }
    }
    
    public static func deserialize(_ infoset: Infoset) -> [DPE_DPE_Gewebe_Organspendeerklaerung] {
        return infoset.map { (element: Infoset) in
        DPE_DPE_Gewebe_Organspendeerklaerung.deserialize(element)
    }
}
}

// utility functions
fileprivate extension String {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> String {
        return infoset.text
    }
}

fileprivate extension Optional where Wrapped == String {
    static func deserialize(_ infoset: Infoset) -> String? {
        if infoset.count == 0 {
            return nil
        } else {
            return String.deserialize(infoset)
        }
    }
}

fileprivate extension Int {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Int {
        guard let ret = Int(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Int {
    static func deserialize(_ infoset: Infoset) -> Int? {
        if infoset.count == 0 {
            return nil
        } else {
            return Int.deserialize(infoset)
        }
    }
}

fileprivate extension Double {
    static let namespacePrefix: String? = nil
    static let namespaceUri: String? = nil
    
    static func deserialize(_ infoset: Infoset) -> Double {
        guard let ret = Double(infoset.text) else {
            return 0
        }
        return ret
    }
}

fileprivate extension Optional where Wrapped == Double {
    static func deserialize(_ infoset: Infoset) -> Double? {
        if infoset.count == 0 {
            return nil
        } else {
            return Double.deserialize(infoset)
        }
    }
}

